import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const denton = localFont({
  src: "../public/Denton.otf",
  variable: "--font-denton",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${denton.className}`}
      >
        {children}
      </body>
    </html>
  );
}
